version: "3.7"

services:
  db_mysql:
    image: mysql
    container_name: mysql
    volumes:
      - db_mysql_volume
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_mysql_volume: {}